(function(){'use strict';
const ROUNDS=100,MATCHES=10;const payoff={CC:[3,3],CD:[0,5],DC:[5,0],DD:[1,1]};
const bots=[
{id:'coop',name:'Всегда сотрудничать',description:'Всегда выбирает сотрудничество.',move:()=> 'C'},
{id:'defect',name:'Всегда предавать',description:'Всегда выбирает предательство.',move:()=> 'D'},
{id:'tit',name:'Око за око',description:'Начинает с C и повторяет последний ход соперника.',move:(round,history)=>round?history[history.length-1].opponent:'C'},
{id:'random',name:'Случайный бот',description:'Выбирает C или D случайно.',move:()=>Math.random()<.5?'C':'D'},
{id:'suspicious',name:'Подозрительное око',description:'Начинает с D, затем отвечает ходом соперника.',move:(round,history)=>round?history[history.length-1].opponent:'D'}];
const $=id=>document.getElementById(id);const ui={leaderboard:$('leaderboard'),pairHead:$('pair-results-head'),pairBody:$('pair-results-body'),tournament:$('run-tournament'),tournamentResult:$('tournament-result'),a:$('bot-a'),b:$('bot-b'),newMatch:$('new-match'),next:$('next-round'),round:$('round-label'),aName:$('bot-a-name'),bName:$('bot-b-name'),aScore:$('bot-a-score'),bScore:$('bot-b-score'),aAction:$('bot-a-action'),bAction:$('bot-b-action'),roundResult:$('round-result')};
const match={a:null,b:null,round:0,aScore:0,bScore:0,history:[]};
function bot(id){return bots.find(item=>item.id===id)}function fillSelectors(){bots.forEach(item=>[ui.a,ui.b].forEach(select=>{const option=document.createElement('option');option.value=item.id;option.textContent=item.name;select.appendChild(option)}));ui.b.value='defect'}
function resetMatch(){match.a=bot(ui.a.value);match.b=bot(ui.b.value);match.round=0;match.aScore=0;match.bScore=0;match.history=[];ui.aName.textContent=match.a.name;ui.bName.textContent=match.b.name;ui.aScore.textContent=0;ui.bScore.textContent=0;ui.aAction.textContent='—';ui.bAction.textContent='—';ui.round.textContent='Раунд 0 / '+ROUNDS;ui.roundResult.textContent='Нажмите «Следующий раунд», чтобы начать.';ui.next.disabled=false}
function playRound(){if(match.round>=ROUNDS)return;const aHistory=match.history.map(item=>({opponent:item.b,action:item.a})),bHistory=match.history.map(item=>({opponent:item.a,action:item.b}));const a=match.a.move(match.round,aHistory),b=match.b.move(match.round,bHistory);const scores=payoff[a+b];match.aScore+=scores[0];match.bScore+=scores[1];match.round++;match.history.push({a,b});ui.aScore.textContent=match.aScore;ui.bScore.textContent=match.bScore;ui.aAction.textContent=a==='C'?'Сотрудничает':'Предаёт';ui.bAction.textContent=b==='C'?'Сотрудничает':'Предаёт';ui.round.textContent='Раунд '+match.round+' / '+ROUNDS;ui.roundResult.textContent='Выплата: '+scores[0]+' / '+scores[1]+' · Счёт: '+match.aScore+' / '+match.bScore;if(match.round===ROUNDS)ui.next.disabled=true}
function playMatch(first,second){const history=[];let scores=[0,0];for(let round=0;round<ROUNDS;round++){const a=first.move(round,history.map(item=>({opponent:item.b,action:item.a}))),b=second.move(round,history.map(item=>({opponent:item.a,action:item.b}))),points=payoff[a+b];scores[0]+=points[0];scores[1]+=points[1];history.push({a,b})}return scores}
function runTournament(){const stats=bots.map(item=>({id:item.id,name:item.name,points:0,wins:0,draws:0,losses:0}));const pairs=bots.map(()=>bots.map(()=>0));for(let i=0;i<bots.length;i++)for(let j=i+1;j<bots.length;j++)for(let game=0;game<MATCHES;game++){const scores=playMatch(bots[i],bots[j]),a=stats[i],b=stats[j];a.points+=scores[0];b.points+=scores[1];pairs[i][j]+=scores[0];pairs[j][i]+=scores[1];if(scores[0]>scores[1]){a.wins++;b.losses++}else if(scores[1]>scores[0]){b.wins++;a.losses++}else{a.draws++;b.draws++}}stats.sort((a,b)=>b.points-a.points);ui.leaderboard.innerHTML=stats.map((item,index)=>'<tr class="'+(index===0?'winner':'')+'"><td>'+(index+1)+'</td><td>'+item.name+'</td><td>'+item.points+'</td><td>'+Math.round(item.points/(MATCHES*(bots.length-1)))+'</td><td>'+item.wins+' / '+item.draws+' / '+item.losses+'</td></tr>').join('');const head='<tr><th scope="col">Стратегия</th>'+bots.map(item=>'<th scope="col">'+item.name+'</th>').join('')+'</tr>';ui.pairHead.innerHTML=head;ui.pairBody.innerHTML=bots.map((item,i)=>'<tr><th scope="row">'+item.name+'</th>'+bots.map((other,j)=>'<td>'+(i===j?'—':pairs[i][j])+'</td>').join('')+'</tr>').join('');ui.tournamentResult.textContent='Лидер эксперимента: '+stats[0].name+'. Рейтинг построен по сумме очков в '+(bots.length*(bots.length-1)/2* MATCHES)+' матчах.'}
window.GAME_THEORY={bots,playMatch,runTournament,resetMatch,playRound};fillSelectors();ui.tournament.addEventListener('click',runTournament);ui.newMatch.addEventListener('click',resetMatch);ui.next.addEventListener('click',playRound);ui.a.addEventListener('change',resetMatch);ui.b.addEventListener('change',resetMatch);resetMatch();})();
